# Home Page Elements
Site_url = "URL:https://www.booking.com/"
Reg_btn = "//header/nav[1]/div[2]/div[5]/a[1]"
Enter_email = "//input[@id='username']"
Email_btn = "//span[contains(text(),'Continue with email')]"
New_pass = "//input[@id='new_password']"
Con_pass = "//input[@id='confirmed_password']"
Create_ac = "//span[contains(text(),'Create account')]"
Click_fb = "//body/div[@id='root']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[4]/div[2]/a[1]"
Click_Google = "//body/div[@id='root']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[4]/div[2]/a[2]"
More_ways = "//button[contains(text(),'More ways to sign in')]"
Click_apple = "//body/div[@id='root']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[4]/div[3]/a[1]"

Signin = "//header/nav[1]/div[2]/div[6]/a[1]/span[1]"

Stays = "//body[1]/header[1]/nav[2]/ul[1]/li[1]/a[1]"
Going = "//input[@id='ss']"
CheckIn = "//body/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/span[1]"
CheckIn_date = "//body[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[3]/div[1]/table[1]/tbody[1]/tr[2]/td[6]"
CheckOut_date = "//body[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[3]/div[1]/table[1]/tbody[1]/tr[3]/td[3]"
DropDown = "//label[@id='xp__guests__toggle']"
Adult_plus = "//body/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]"
Adult_minus = "//body/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]"
Child_plus = "//body/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/button[2]"
Child_minus = "//body/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/button[1]"
Room_plus = "//body/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[4]/div[1]/div[2]/button[2]"
Room_minus = "//body/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[4]/div[1]/div[2]/button[1]"

Flight_btn = "//header/nav[2]/ul[1]/li[2]/a[1]"
Trip = "//div[@data-value='roundtrip']"

Car_btn = "//header/nav[2]/ul[1]/li[3]/a[1]"
Radio_Same_loc = "//label[contains(text(),'Return to same location')]"
Radio_diff_loc = "//label[contains(text(),'Return to different location')]"
Pick_loc = "//input[@id='ss_origin']"
Drop_loc = "//input[@id='ss']"
Click_Pickup_date = "//body/div[@id='bodyconstraint']/div[@id='bodyconstraint-inner']/div[3]/div[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]"
Click_Dropup_date = "//body/div[@id='bodyconstraint']/div[@id='bodyconstraint-inner']/div[3]/div[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[3]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/button[1]"
Pickup_date = "//body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[3]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[2]/div[3]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[3]/span[1]"
Dropup_date = "//body[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[3]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[2]/div[3]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[5]/span[1]"

Attr_btn = "//header/nav[2]/ul[1]/li[4]/a[1]"
Find_place = "//body/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/form[1]/div[1]/input[1]"
Click_Search = "//span[contains(text(),'Search')]"

Airport_btn = "//header/nav[2]/ul[1]/li[5]/a[1]"
